### ISSUE TITLE
The output image is not dewarped

### ISSUE THREAD

**Issue by zye1996** [stnamjef/page_dewarp#2]
Hi I tried the code and the output is not dewarped but simply threshed. Are there any settings to tweak with?

**Comment by zvezdochiot** [comment]
```sh
page_dewarp
```
and see help:
```
-m 0
```

**Comment by zye1996** [comment]
> ```shell
> page_dewarp
> ```
> 
> and see help:
> 
> ```
> -m 0
> ```

I found the problem, at this [line](https://github.com/stnamjef/page_dewarp/blob/116da60699877c58b28151d7888aaec8d20269f4/source/page_dewarp.h#L678)

I believe you mean ```cv::adaptiveThreshold(remapped, thresh, 255, ADAPTIVE_THRESH_MEAN_C, THRESH_BINARY, ADAPTIVE_WINSZ, 25);```

**Comment by zvezdochiot** [comment]
Replace:
https://github.com/stnamjef/page_dewarp/blob/116da60699877c58b28151d7888aaec8d20269f4/source/page_dewarp.h#L678
to
```sh
		cv::adaptiveThreshold(remapped, thresh, 255, ADAPTIVE_THRESH_MEAN_C, THRESH_BINARY, ADAPTIVE_WINSZ, 25);
```

**Comment by zvezdochiot** [comment]
Also use:
```sh
-ro
```

**Comment by stnamjef** [comment]
I just fixed the bug. Thanks to @zye1996 and @zvezdochiot for reporting it.
