### ISSUE TITLE
dewarp problem

### ISSUE THREAD

**Issue by cloudfool** [stnamjef/page_dewarp#3]
Hi,
I tested your code and found it doesn't work on this pic. Could you pls give me some advice?TKS

![linguistics_thesis_b](https://user-images.githubusercontent.com/22359737/130038247-3ce7d021-e1be-4848-bd3c-e6f47b361442.jpg)
![linguistics_thesis_b_thresh](https://user-images.githubusercontent.com/22359737/130038253-6aca82af-9a27-4d29-ab47-1ff4d9f2b279.png)

**Comment by zvezdochiot** [comment]
Hi @cloudfool .

Use option `-m 0`.

**Comment by cloudfool** [comment]
Hi, @zvezdochiot 
I used this option but found code aborted. Could you pls test this pic for me and show me your result ?

**Comment by zvezdochiot** [comment]
Hi @cloudfool .

Not, wait for the author. 

PS: I have my own craft: https://github.com/ImageProcessing-ElectronicPublications/pagedewarp . The other is not of interest.

**Comment by stnamjef** [comment]
I added a CLI option for "table" type image.

You can set `-it=table` to dewarp the image above.

Let me know if you have any other issues.
